### ISSUE TITLE
fix handling if no slug is provided

### ISSUE THREAD

**Issue by sknebel** [capjamesg/indieweb-etherpad-archiver#1]
right now it then uses a default slug of "0", which doesn't make much sense.

cf https://chat.indieweb.org/meta/2023-01-12#t1673567042961800

**Comment by capjamesg** [comment]
This issue has been resolved in [69fcf6b](https://github.com/capjamesg/indieweb-etherpad-archiver/commit/69fcf6b81fa185699f2ac3a06054123b24cc45a3). Now, if no slug is found, a message is sent to inform a user of the correct syntax for using the function.

**Comment by capjamesg** [comment]
This is a test comment.

(Originally published at: https://jamesg.coffee/2023/this-is-a-test-comment)

**Comment by sknebel** [comment]
test comment received 😝

**Comment by capjamesg** [comment]
This is another test comment.

&lt;a href="https://brid.gy/publish/github"&gt;&lt;/a&gt;

(Originally published at: https://jamesg.coffee/2023/this-is-another-test-comment)
