### ISSUE TITLE
Warn if event or Etherpad link already archived

### ISSUE THREAD

**Issue by tantek** [capjamesg/indieweb-etherpad-archiver#5]
If someone in chat issues a !archive command on an event or Etherpad URL (per [issue 4](https://github.com/capjamesg/indieweb-etherpad-archiver/issues/4)), and it has already been archived (the destination wiki URL already exists), the bot should return with a warning that the event has already been archived, and provide the full wiki URL for the chat user to inspect, and manually make any improvements if necessary. Requested originally in IndieWeb meta chat, [earlier today](https://chat.indieweb.org/meta/2023-04-10#t1681162290848100).

(Originally published at: https://tantek.com/2023/100/b1/)

**Comment by capjamesg** [comment]
This feature was since implemented so I am closing this issue.
